name: LDVM CI
on: [push]
jobs:
  # Test on various OS with default Go version.
  tests:
    name: Test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        go-version: ["1.19"]

    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Print Go version
      run: go version

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Run tests
      run: ./scripts/build_test.sh

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        verbose: true
